baseURL = 'https://blog.dobron.sk'
languageCode = 'en-us'
title = "Sam's Notes"
theme = 'hugo-theme-terminal'

pagination.pagerSize = 5

enableRobotsTXT = true

# Required for Chroma and the custom syntax highlighting.
[markup.highlight]
  noClasses = false

[params]
  # GitHub repository for version links (format: username/repo-name)
  gitRepo = "enhaut/blog"

  # Site author
  author = "Samuel Dobro≈à"

  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = false

  # if your resource directory contains an image called `cover.(jpg|png|webp)`,
  # then the file will be used as a cover automatically.
  # With this option you don't have to put the `cover` param in a front-matter.
  autoCover = true

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = true
  enableGitInfo = true

  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  updatedDatePrefix = "Updated"

  # whether to show a page's estimated reading time
  readingTime = true # default

  # text to show in read more link
  readMore = "..."
